
import Link from "next/link";
import ProductCard from "@/components/ProductCard";
import { getProducts, getSiteContent } from "@/lib/data-store";
export default function HomePage(){ const products=getProducts(); const site=getSiteContent(); const featured=products.filter(i=>i.featured).slice(0,4); const trending=products.filter(i=>i.trending).slice(0,4);
 return <main><section className="hero-section"><div className="container hero-grid"><div><div className="eyebrow">{site.hero.eyebrow}</div><h1 className="hero-title">{site.hero.title}</h1><p className="hero-subtitle">{site.hero.subtitle}</p><form action="/search" className="hero-search"><input name="q" placeholder={site.hero.searchPlaceholder} /><button type="submit">Search</button></form><div className="quick-row">{site.hero.quickSearches.map(term=><Link key={term} href={`/search?q=${encodeURIComponent(term)}`} className="quick-pill">{term}</Link>)}</div></div><div className="hero-panel"><div className="promo-card large"><span className="promo-badge">{site.sections.announcement}</span><h3>Marketplace layout with manual product management</h3><p>Import product title, price, image link, seller info, stock, and badges from the admin panel.</p></div><div className="stat-grid">{site.hero.stats.map(item=><div key={item.label} className="stat-card"><strong>{item.value}</strong><span>{item.label}</span></div>)}</div></div></div></section>
 <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Featured</div><h2>Highlighted products</h2></div><Link href="/products" className="text-link">See all products</Link></div><div className="product-grid">{featured.map(product=><ProductCard key={product.id} product={product} />)}</div></div></section>
 <section className="section muted"><div className="container three-col">{site.sections.featureCards.map(card=><div className="info-card" key={card.title}><h3>{card.title}</h3><p>{card.text}</p></div>)}</div></section>
 <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Popular now</div><h2>Trending listings</h2></div></div><div className="product-grid">{trending.map(product=><ProductCard key={product.id} product={product} />)}</div></div></section></main>; }
